import { MobileProject } from '../../../domain/entities/project.entity';

export const rawProjectsData: MobileProject[] = [
  {
    id: 'umama-super-app',
    title: 'Umama HRIS',
    subtitle: 'Official Employee Self-Service (ESS) & Enterprise HRIS Platform',
    client: 'Umama • PT Umama Karya Nusantara',
    category: 'Enterprise HRIS',
    role: 'Mobile Developer (Flutter)',
    period: '2026',
    isFeatured: true,
    platform: ['Flutter', 'Android Native', 'iOS'],
    summary: 'The official enterprise employee self-service (ESS) and human resource management platform designed for the Umama team, empowering hundreds of employees across retail fashion branches and headquarters to manage daily attendance, leave requests, cash advances (kasbon), expense reimbursements, and encrypted digital payslips.',
    architecturalHighlights: [
      'Feature-First Clean Architecture with Flutter BLoC, Hydrated BLoC, and Domain-Driven Design (DDD) principles',
      'Robust Dio HTTP network layer with automatic JWT token refresh interceptors, mutex locking, and Dartz (Either<Failure, Success>) error handling',
      'Encrypted local session vault with flutter_secure_storage and GoRouter declarative navigation with auth guards',
      'End-to-end multi-tier approval workflow engine for internal cash advances (kasbon requests & settlements) and operational claims',
    ],
    challenges: [
      {
        title: 'Token Refresh Mutex & High-Concurrency Request Synchronization',
        problem: 'When multiple simultaneous background services and UI requests fired with an expired access token, multiple parallel refresh token calls were triggered, causing session invalidation.',
        engineeringSolution: 'Implemented a synchronized mutex lock queue in the custom Dio interceptor that holds outgoing requests until a single refresh call succeeds, then retries queued requests seamlessly.',
      },
      {
        title: 'Atomic Multi-Tier Workflow for Cash Advances (Kasbon) & Settlements',
        problem: 'Managing complex lifecycle states across submission, department approval, finance disbursement, and receipt settlement with offline resilience.',
        engineeringSolution: 'Engineered dedicated Freezed state unions in BLoC paired with local Hydrated caching, ensuring zero state inconsistencies even during connectivity disruptions.',
      },
    ],
    metrics: [
      {
        label: 'Active Staff',
        value: '1,000+',
        detail: 'Employees across retail stores and HQ',
      },
      {
        label: 'Approval Speed',
        value: '3x Faster',
        detail: 'Streamlined multi-tier HR approvals',
      },
      {
        label: 'Crash-Free Rate',
        value: '99.9%',
        detail: 'Monitored via Firebase Crashlytics',
      },
    ],
    techStack: {
      languages: ['Dart', 'Kotlin', 'Swift'],
      frameworks: ['Flutter 3.x'],
      stateManagement: ['Flutter BLoC', 'Hydrated BLoC', 'Freezed'],
      localDbAndStorage: ['Flutter Secure Storage', 'Shared Preferences'],
      architecturePatterns: ['Feature-First Clean Architecture', 'Domain-Driven Design (DDD)', 'Repository Pattern'],
      integrations: ['Dio + Token Interceptors', 'GetIt Service Locator', 'GoRouter', 'Firebase Cloud Messaging', 'Dartz'],
    },
    screens: [
      {
        id: 'umama-login',
        title: 'Login Portal',
        caption: 'Autentikasi akun karyawan terintegrasi dengan kredensial perusahaan',
        type: 'auth',
        accentColor: '#B70603',
        imageSrc: '/assets/projects/umama/login.jpg',
      },
      {
        id: 'umama-home',
        title: 'Home & Clock-In',
        caption: 'Dashboard utama: jam kerja, status absensi & tombol presensi harian',
        type: 'dashboard',
        accentColor: '#B70603',
        imageSrc: '/assets/projects/umama/home.jpg',
      },
      {
        id: 'umama-requests',
        title: 'Kasbon & Requests',
        caption: 'Pusat pengajuan: kasbon (cash advance), klaim reimbursement & cuti',
        type: 'form',
        accentColor: '#B70603',
        imageSrc: '/assets/projects/umama/requests.jpg',
      },
      {
        id: 'umama-calendar',
        title: 'Work Calendar',
        caption: 'Kalender kerja bulanan: status kehadiran, absensi, cuti & hari libur',
        type: 'analytics',
        accentColor: '#B70603',
        imageSrc: '/assets/projects/umama/calendar.jpg',
      },
      {
        id: 'umama-profile',
        title: 'Profile & ID',
        caption: 'Profil karyawan: kartu identitas digital & akses rincian slip gaji',
        type: 'profile',
        accentColor: '#B70603',
        imageSrc: '/assets/projects/umama/profile.jpg',
      },
      {
        id: 'umama-inbox',
        title: 'Announcements',
        caption: 'Kotak masuk pengumuman resmi dan surat keputusan internal',
        type: 'dashboard',
        accentColor: '#B70603',
        imageSrc: '/assets/projects/umama/inbox.jpg',
      },
    ],
  },
  {
    id: 'daai-plus',
    title: 'DAAI+',
    subtitle: 'Official Mobile Streaming Platform & Gamified Content Ecosystem',
    client: 'DAAI+ • PT DUTA ANUGERAH INDAH',
    category: 'Streaming & Media',
    role: 'Mobile Developer (Flutter)',
    period: '2026',
    isFeatured: true,
    platform: ['Flutter', 'Android Native', 'iOS'],
    summary: 'The official mobile streaming and Video-on-Demand (VOD) platform from DAAI TV Indonesia, delivering 24/7 high-definition live television broadcasts, inspirational series, uplifting news, interactive real-time live chat rooms via WebSockets, offline SQLite caching with Drift, gamified loyalty missions ("Misi Kebaikan"), and QR-code Smart TV cross-device authentication.',
    architecturalHighlights: [
      'Robust reactive state management powered by Riverpod (flutter_riverpod) orchestrating media streams, real-time chats, and multi-flavor app environments (dev/staging/prod)',
      'Custom HLS & MP4 VOD Playback Engine built on Chewie and video_player with dynamic resolution switching, episode retention tracking, and interactive video sponsor overlays',
      'Real-Time Bi-Directional WebSocket Chat Room with Drift SQLite offline message caching, voice note recording/playback, user tier badges, and reaction stickers',
      'Gamification & Loyalty Rewards Engine supporting daily check-ins, watering mini-games ("Siram Tanaman"), reward point accumulation, and DAAI Shop voucher redemption',
      'Cross-Device Smart TV Companion Pairing using Mobile Scanner QR recognition for instant zero-friction TV login authorization',
    ],
    challenges: [
      {
        title: 'High-Frequency WebSocket Live Chat & Offline Sync',
        problem: 'Managing high volumes of incoming chat messages, reaction stickers, and voice notes during live TV broadcasts without stuttering video playback or causing UI thread memory spikes.',
        engineeringSolution: 'Implemented an asynchronous Drift SQLite buffer layer paired with Riverpod state streaming and throttled UI updates, isolating live stream rendering from real-time messaging thread activity.',
      },
      {
        title: 'Seamless Cross-Device Smart TV QR Handshake',
        problem: 'Enabling secure, rapid token exchange between the mobile device and big-screen TV app without exposing sensitive user credentials or requiring tedious TV remote typing.',
        engineeringSolution: 'Architected a secure ephemeral QR pairing flow using encrypted short-lived tokens and WebSocket handshake verification, completing cross-device authentication in under 2 seconds.',
      },
    ],
    metrics: [
      {
        label: 'Downloads',
        value: '100K+',
        detail: 'Android Play Store & iOS App Store',
      },
      {
        label: 'Live Broadcast',
        value: '24/7 HD',
        detail: 'Continuous low-latency HLS stream',
      },
      {
        label: 'Pairing Speed',
        value: '< 2s',
        detail: 'Instant Smart TV QR authorization',
      },
    ],
    techStack: {
      languages: ['Dart', 'Kotlin', 'Swift'],
      frameworks: ['Flutter 3.x'],
      stateManagement: ['Riverpod (flutter_riverpod)'],
      localDbAndStorage: ['Drift (SQLite)', 'Shared Preferences'],
      architecturePatterns: ['Feature-Driven Layered Architecture', 'Repository Pattern', 'Service Layer Pattern'],
      integrations: [
        'Dio HTTP Client',
        'Native WebSocket Channels',
        'Chewie & video_player',
        'mobile_scanner & qr_flutter',
        'Firebase Cloud Messaging',
        'Google & Apple OAuth2',
        'App Links (Deep Linking)',
        'Firebase Analytics',
      ],
    },
    screens: [
      {
        id: 'daai-login',
        title: 'Login Portal',
        caption: 'Autentikasi akun multi-metode dengan Google Sign-In & Apple OAuth',
        type: 'auth',
        accentColor: '#F59E0B',
        imageSrc: '/assets/projects/daai/0.jpg',
      },
      {
        id: 'daai-home',
        title: 'Beranda & VOD',
        caption: 'Katalog serial inspiratif, tayangan budaya humanis & fitur Lanjut Nonton',
        type: 'dashboard',
        accentColor: '#F59E0B',
        imageSrc: '/assets/projects/daai/1.jpg',
      },
      {
        id: 'daai-live',
        title: 'Live TV 24/7',
        caption: 'Streaming langsung saluran DAAI TV & Tzu Chi lengkap dengan jadwal EPG',
        type: 'dashboard',
        accentColor: '#F59E0B',
        imageSrc: '/assets/projects/daai/2.jpg',
      },
      {
        id: 'daai-news',
        title: 'Berita & Inspirasi',
        caption: 'Artikel terkini aksi kemanusiaan, pelestarian lingkungan, dan kesehatan',
        type: 'dashboard',
        accentColor: '#F59E0B',
        imageSrc: '/assets/projects/daai/3.jpg',
      },
      {
        id: 'daai-search',
        title: 'Pencarian Terpadu',
        caption: 'Pencarian cepat untuk film, program acara, tayangan Lentera Kehidupan & artikel',
        type: 'dashboard',
        accentColor: '#F59E0B',
        imageSrc: '/assets/projects/daai/4.jpg',
      },
      {
        id: 'daai-detail',
        title: 'Detail Serial & Player',
        caption: 'Player video VOD kustom dengan sinopsis alur cerita, daftar episode & opsi share',
        type: 'dashboard',
        accentColor: '#F59E0B',
        imageSrc: '/assets/projects/daai/5.jpg',
      },
      {
        id: 'daai-shop',
        title: 'Toko & Poin Hadiah',
        caption: 'Gamifikasi Misi Kebaikan dan katalog penukaran poin untuk voucher & merchandise',
        type: 'form',
        accentColor: '#F59E0B',
        imageSrc: '/assets/projects/daai/6.jpg',
      },
      {
        id: 'daai-merch',
        title: 'Detail Merchandise',
        caption: 'Halaman penukaran poin reward untuk produk fisik eksklusif DAAI TV',
        type: 'form',
        accentColor: '#F59E0B',
        imageSrc: '/assets/projects/daai/7.jpg',
      },
      {
        id: 'daai-chat',
        title: 'Live Chat Room',
        caption: 'Ruang obrolan real-time interaktif pemirsa via WebSockets dengan stiker & voice notes',
        type: 'dashboard',
        accentColor: '#F59E0B',
        imageSrc: '/assets/projects/daai/8.jpg',
      },
      {
        id: 'daai-notif',
        title: 'Pusat Notifikasi',
        caption: 'Pengingat episode baru, misi harian Tanam Kebaikan & pengumuman broadcast',
        type: 'dashboard',
        accentColor: '#F59E0B',
        imageSrc: '/assets/projects/daai/9.jpg',
      },
    ],
    links: {
      playStore: 'https://play.google.com/store/apps/details?id=com.daaitv.daaiplus&hl=en',
      appStore: 'https://apps.apple.com/id/app/daai/id1607047602',
    },
  },
  {
    id: 'mitsubishi-motors-id',
    title: 'My Mitsubishi Motors ID 2.0',
    subtitle: 'Official Customer Companion App & Vehicle Telematics Platform',
    client: 'PT Mitsubishi Motors Krama Yudha Sales Indonesia (MMKSI)',
    category: 'Automotive',
    role: 'Mobile Developer (Flutter)',
    period: '2022 - 2024',
    isFeatured: true,
    platform: ['Flutter', 'Android Native', 'iOS'],
    summary: 'Official cross-platform mobile application developed using Flutter for PT Mitsubishi Motors Krama Yudha Sales Indonesia (MMKSI). Provides vehicle information, warranty activation, real-time service booking, interactive dealer locator, 24-hour emergency assistance (Bengkel Siaga SOS), and digital service reminders.',
    architecturalHighlights: [
      'Cross-platform architecture developed with Flutter and BLoC state management for seamless cross-module isolation',
      'Real-time workshop service booking engine with dealer network locator and slot reservation',
      '24-Hour Bengkel Siaga SOS emergency roadside assistance with background geocoding',
      'Vehicle information, warranty activation, and digital service reminder system',
    ],
    challenges: [],
    metrics: [],
    techStack: {
      languages: ['Dart', 'Kotlin', 'Swift'],
      frameworks: ['Flutter 3.x'],
      stateManagement: ['Flutter BLoC', 'Freezed'],
      localDbAndStorage: ['Hive', 'Flutter Secure Storage'],
      architecturePatterns: ['Clean Architecture', 'Repository Pattern', 'Feature-First Modularity'],
      integrations: ['Google Maps SDK', 'Firebase Cloud Messaging', 'OAuth2 Single Sign-On', 'RESTful API'],
    },
    screens: [
      {
        id: 'mm-dashboard',
        title: 'Vehicle Garage',
        caption: 'Vehicle telemetry, warranty health, and quick service actions',
        type: 'dashboard',
        accentColor: '#E60012',
        previewUiData: {
          headerTitle: 'My Mitsubishi Motors',
          subheading: 'All New Pajero Sport (D1234SSS)',
          badge: 'ACTIVE WARRANTY',
          statusText: 'Next Service: In 1,200 Km',
          actionLabel: 'Book Service Workshop',
          stats: [
            { label: 'Odometer', value: '18,450 km' },
            { label: 'Warranty', value: '2027 Valid' },
            { label: 'Coupons', value: '3 Active' },
          ],
          listItems: [
            { title: 'Periodic Maintenance #4', subtitle: 'Mahligai - Cimahi Dealer', status: 'Scheduled', tag: 'Service' },
            { title: '24-Hour Bengkel Siaga', subtitle: 'Ready 24/7 Nationwide', status: 'Available', tag: 'Emergency' },
            { title: 'Silver Service Voucher', subtitle: 'Save Rp 250.000', status: 'Claimed', tag: 'Promo' },
          ],
        },
      },
      {
        id: 'mm-booking',
        title: 'Service Booking',
        caption: 'Interactive workshop locator, dealer calendar, and technician service packages',
        type: 'booking',
        accentColor: '#E60012',
        previewUiData: {
          headerTitle: 'Service Reservation',
          subheading: 'Select Dealership & Schedule',
          badge: 'DEALER CONFIRMED',
          statusText: 'Mahligai Cimahi (2.4 km away)',
          actionLabel: 'Confirm Appointment',
          stats: [
            { label: 'Date', value: 'Tomorrow' },
            { label: 'Slot', value: '09:00 WIB' },
            { label: 'Bay', value: 'Quick Pit 2' },
          ],
          listItems: [
            { title: 'Engine Oil & Filter Replacement', subtitle: 'Synthetic 0W-20 Genuine Oil', tag: 'Mandatory' },
            { title: 'Brake Fluid & Pad Inspection', subtitle: 'Full front & rear caliper check', tag: 'Safety' },
            { title: '28-Point Multi-Check System', subtitle: 'Electronic OBD Diagnostic scan', tag: 'Complimentary' },
          ],
        },
      },
      {
        id: 'mm-emergency',
        title: '24H Bengkel Siaga',
        caption: 'One-tap emergency roadside assistance with GPS dispatch coordinates',
        type: 'map',
        accentColor: '#E60012',
        previewUiData: {
          headerTitle: 'Emergency Rescue',
          subheading: '24-Hour Roadside Assistance',
          badge: 'DISPATCH READY',
          statusText: 'Nearest Patrol: 12 min ETA',
          actionLabel: 'Call SOS Dispatcher',
          stats: [
            { label: 'GPS Precision', value: '±3 meters' },
            { label: 'Response', value: '< 15 Min' },
            { label: 'Towing', value: 'Covered' },
          ],
          listItems: [
            { title: 'Battery Jumper & Electrical', subtitle: 'On-site mobile diagnostic van', status: 'Active', tag: 'Rescue' },
            { title: 'Tire Flat Replacement', subtitle: 'Hydraulic jack & wheel balancing', status: 'Active', tag: 'Tire' },
            { title: 'Emergency Fuel Delivery', subtitle: '5L Diesel / Gasoline delivery', status: 'Standby', tag: 'Fuel' },
          ],
        },
      },
    ],
    links: {
      playStore: 'https://play.google.com/store/apps/details?id=id.co.mitsubishimotors.customer',
      appStore: 'https://apps.apple.com/id/app/my-mitsubishi-motors-id/id1504930366',
    },
  },
  {
    id: 'nolimit-engage',
    title: 'NoLimit Engage',
    subtitle: 'Influencer Management, Collaboration & Social Media Analytics Platform',
    client: 'NoLimit Indonesia • PT Samudra Data Nusantara',
    category: 'Social Analytics',
    role: 'Mobile Developer (Flutter)',
    period: '2023 - 2024',
    isFeatured: true,
    platform: ['Flutter', 'Android Native', 'iOS'],
    summary: 'Comprehensive cross-platform Influencer Management application developed using Flutter for NoLimit Indonesia. Features Influencer Discovery & Collaboration to expand brand reach effectively, advanced data analytics for performance tracking, audience insights, campaign optimization, and field inspection support for on-site data collection and reporting.',
    architecturalHighlights: [
      'Comprehensive Influencer Discovery & Collaboration directory to expand brand reach',
      'Advanced Data Analytics pipeline for performance tracking, audience insights, and campaign optimization',
      'Field inspection workflow supporting efficient on-site data collection and campaign proof reporting',
      'Performance monitoring and real-time metric optimization to refine marketing strategies',
    ],
    challenges: [],
    metrics: [],
    techStack: {
      languages: ['Dart', 'Kotlin'],
      frameworks: ['Flutter 3.x'],
      stateManagement: ['Flutter BLoC', 'Provider'],
      localDbAndStorage: ['Hive', 'Isar DB'],
      architecturePatterns: ['Clean Architecture', 'Repository Pattern', 'CQRS Lite'],
      integrations: ['FlChart Custom Engine', 'RESTful API', 'Multipart Upload Manager', 'Firebase Analytics'],
    },
    screens: [
      {
        id: 'nolimit-analytics',
        title: 'Campaign Analytics',
        caption: 'Real-time reach, engagement rates, sentiment distribution, and conversion tracking',
        type: 'analytics',
        accentColor: '#0088FF',
        previewUiData: {
          headerTitle: 'NoLimit Engage',
          subheading: 'Campaign: Ramadhan Mega Sale 2024',
          badge: 'CAMPAIGN ACTIVE',
          statusText: 'Overall Sentiment: 94.2% Positive',
          actionLabel: 'Export Campaign Report',
          stats: [
            { label: 'Total Reach', value: '4.8M' },
            { label: 'Engagement', value: '6.4%' },
            { label: 'Creators', value: '42 Active' },
          ],
          listItems: [
            { title: 'Instagram Reels Wave 1', subtitle: '28 Posts • 1.2M Impressions', status: 'Completed', tag: 'IG' },
            { title: 'TikTok Creator Challenge', subtitle: '65 Videos • 3.1M Views', status: 'Trending', tag: 'TikTok' },
            { title: 'YouTube Long-form Review', subtitle: '4 Videos • 500K Views', status: 'In Review', tag: 'YT' },
          ],
        },
      },
      {
        id: 'nolimit-influencer',
        title: 'Influencer Directory',
        caption: 'Granular search, engagement rate verification, and direct contract initiation',
        type: 'dashboard',
        accentColor: '#0088FF',
        previewUiData: {
          headerTitle: 'Creator Discovery',
          subheading: 'Filter by Niche, Reach & ER',
          badge: 'VERIFIED CREATORS',
          statusText: '1,420 Creators match criteria',
          actionLabel: 'Add to Campaign Roster',
          stats: [
            { label: 'Niche', value: 'Tech & Auto' },
            { label: 'Avg ER', value: '7.8%' },
            { label: 'Authenticity', value: '98%' },
          ],
          listItems: [
            { title: 'TechReviewer Indonesia', subtitle: '450K Followers • 8.4% ER', status: 'Available', tag: 'Top Tier' },
            { title: 'Gadget Lifestyle ID', subtitle: '280K Followers • 6.9% ER', status: 'Active Campaign', tag: 'Mid Tier' },
            { title: 'Automotive Enthusiast', subtitle: '190K Followers • 9.1% ER', status: 'Available', tag: 'High ER' },
          ],
        },
      },
    ],
  },
  {
    id: 'akselhr-app',
    title: 'AtlasHR (AkselHR)',
    subtitle: 'Enterprise Human Resource Information System & Workforce Management App',
    client: 'PT Radya Anugrah Digital',
    category: 'Enterprise HRIS',
    role: 'Mobile Developer (Flutter)',
    period: '2022 - 2024',
    isFeatured: true,
    platform: ['Flutter', 'Android Native', 'iOS'],
    summary: 'Cross-platform enterprise human resource management application developed using Flutter as a company product of PT Radya Anugrah Digital. Designed to streamline HR operations and improve workforce efficiency by supporting employee management including attendance tracking, leave requests, overtime, reimbursements, and payslip access.',
    architecturalHighlights: [
      'Employee attendance tracking with geofenced location verification and shift matching',
      'Comprehensive leave, overtime, and operational reimbursement request workflows',
      'Encrypted digital payslip access with biometric security authentication',
      'Engineered to streamline enterprise HR operations and improve workforce efficiency',
    ],
    challenges: [],
    metrics: [],
    techStack: {
      languages: ['Dart', 'Kotlin', 'Swift'],
      frameworks: ['Flutter 3.x'],
      stateManagement: ['Flutter BLoC', 'Riverpod'],
      localDbAndStorage: ['Hive', 'Biometric Auth Storage'],
      architecturePatterns: ['Clean Architecture', 'Repository Pattern'],
      integrations: ['Google Maps Geofencing', 'Local Biometric SDK', 'Firebase Cloud Messaging', 'RESTful API'],
    },
    screens: [
      {
        id: 'aksel-home',
        title: 'Employee Portal',
        caption: 'Clock-in status, geofenced office boundary, shift schedule, and leave balances',
        type: 'dashboard',
        accentColor: '#0066FF',
        previewUiData: {
          headerTitle: 'AtlasHR Mobile',
          subheading: 'Good Morning, Andi Pratama',
          badge: 'IN OFFICE GEOFENCE',
          statusText: 'Clock-in: 08:52 WIB (On-time)',
          actionLabel: 'Clock-Out Attendance',
          stats: [
            { label: 'Work Hours', value: '7h 45m' },
            { label: 'Leave Balance', value: '12 Days' },
            { label: 'Claims', value: '2 Pending' },
          ],
          listItems: [
            { title: 'Headquarters Office Hub', subtitle: 'Within 25m Radius Geofence', status: 'Verified', tag: 'GPS' },
            { title: 'Annual Leave Request', subtitle: '3 Days (14 - 16 Oct 2024)', status: 'Approved', tag: 'Leave' },
            { title: 'Medical Optical Claim', subtitle: 'Rp 750.000 • HR Review', status: 'Processing', tag: 'Claim' },
          ],
        },
      },
      {
        id: 'aksel-calendar',
        title: 'Attendance Calendar',
        caption: 'Monthly productivity analysis, shift schedules, overtime, and punctuality scoring',
        type: 'analytics',
        accentColor: '#0066FF',
        previewUiData: {
          headerTitle: 'Activity & Roster',
          subheading: 'Monthly Punctuality: 98.4%',
          badge: 'EXCELLENT ATTENDANCE',
          statusText: '22 Days Present • 0 Absent',
          actionLabel: 'Request Overtime Slip',
          stats: [
            { label: 'Productive', value: '96%' },
            { label: 'Overtime', value: '4.5 Hours' },
            { label: 'Late Count', value: '0' },
          ],
          listItems: [
            { title: 'Sprint Delivery Overtime', subtitle: '2 Hours • Manager Approved', status: 'Verified', tag: 'Overtime' },
            { title: 'Client On-Site Visit', subtitle: 'Bandung Tech Hub Branch', status: 'Logged', tag: 'Visit' },
            { title: 'Biometric Payslip Ready', subtitle: 'September 2024 Salary Slip', status: 'Encrypted', tag: 'Payroll' },
          ],
        },
      },
    ],
  },
  {
    id: 'imuni-app',
    title: 'Imuni',
    subtitle: 'On-Demand Vaccination Scheduling & Digital Health Records Platform',
    client: 'Imuni Indonesia',
    category: 'HealthTech',
    role: 'Mobile Developer (Flutter)',
    period: '2023',
    isFeatured: true,
    platform: ['Flutter', 'iOS', 'Android Native'],
    summary: 'Cross-platform medical application developed using Flutter, enabling users to schedule vaccinations and track health records. Designed to improve health management and accessibility across Indonesia.',
    architecturalHighlights: [
      'Interactive vaccination scheduling engine for home visits and clinic appointments',
      'Comprehensive digital immunization records and family health tracking',
      'Automated vaccination milestone reminders and doctor consultation records',
      'Designed to improve pediatric health management and healthcare accessibility',
    ],
    challenges: [],
    metrics: [],
    techStack: {
      languages: ['Dart', 'Kotlin'],
      frameworks: ['Flutter 3.x'],
      stateManagement: ['GetX', 'Provider'],
      localDbAndStorage: ['Hive', 'Shared Preferences'],
      architecturePatterns: ['Clean Architecture', 'MVC / MVVM'],
      integrations: ['Google Maps API', 'Firebase Cloud Messaging', 'Custom Chart Engine', 'REST API'],
    },
    screens: [
      {
        id: 'imuni-growth',
        title: 'Growth Tracker',
        caption: 'WHO percentile growth curves, milestone tracking, and doctor recommendations',
        type: 'analytics',
        accentColor: '#E91E63',
        previewUiData: {
          headerTitle: 'Imuni Pediatric',
          subheading: 'Child: Rayyan Iqbal (18 Months)',
          badge: 'HEALTHY GROWTH',
          statusText: 'All developmental milestones on track',
          actionLabel: 'Schedule Vaccine Visit',
          stats: [
            { label: 'Weight', value: '11.4 kg (P50)' },
            { label: 'Height', value: '84 cm (P50)' },
            { label: 'Next Due', value: 'DTP Booster' },
          ],
          listItems: [
            { title: 'DTP - Hib - HepB Booster', subtitle: 'Recommended at 18 Months', status: 'Due Soon', tag: 'Vaccine' },
            { title: 'MMR Measles & Rubella', subtitle: 'Administered at 15 Months', status: 'Completed', tag: 'History' },
            { title: 'Polio Oral Vaccine #4', subtitle: 'Administered at 12 Months', status: 'Completed', tag: 'History' },
          ],
        },
      },
    ],
  },
  {
    id: 'visual-inspection-system-pupr',
    title: 'Visual Inspection System',
    subtitle: 'National Road Infrastructure Damage Mapping & Offline Field Inspection App',
    client: 'Kementerian Pekerjaan Umum (PUPR)',
    category: 'GovTech & Infrastructure',
    role: 'Android Developer (Kotlin / Java)',
    period: '2021 - 2022',
    isFeatured: false,
    platform: ['Android Native', 'Kotlin', 'Java'],
    summary: 'Android native application developed with Kotlin using MVP/MVVM architecture for Kementerian Pekerjaan Umum (PUPR). Features an interactive Mapbox map to mark and display road damage locations, implements local storage using Room Database for offline data handling with manual synchronization, and supports field inspections by enabling efficient data collection and reporting to enhance road infrastructure monitoring and maintenance.',
    architecturalHighlights: [
      'Android native architecture developed in Kotlin with MVP/MVVM design patterns',
      'Interactive map (Mapbox) to mark and display road damage locations on national highways',
      'Local storage with Room Database for offline-first data handling and manual synchronization',
      'Field inspection toolset enabling efficient data collection and reporting for infrastructure maintenance',
    ],
    challenges: [],
    metrics: [],
    techStack: {
      languages: ['Kotlin', 'Java'],
      frameworks: ['Android SDK', 'Android Jetpack'],
      stateManagement: ['Android ViewModel', 'LiveData'],
      localDbAndStorage: ['Room Database', 'SQLite', 'Encrypted SharedPrefs'],
      architecturePatterns: ['MVVM Architecture', 'Repository Pattern', 'Offline-First Synchronization'],
      integrations: ['Mapbox SDK', 'Android WorkManager', 'CameraX', 'Retrofit2 / OkHttp3'],
    },
    screens: [
      {
        id: 'vis-map',
        title: 'GIS Damage Map',
        caption: 'Interactive vector map with offline road topology and damage point markers',
        type: 'map',
        accentColor: '#E6A100',
        previewUiData: {
          headerTitle: 'Visual Inspection System',
          subheading: 'JICA - Regional Roads Governance',
          badge: 'OFFLINE MODE ACTIVE',
          statusText: 'GPS Lock: ±2.1m (Cimahi - Padalarang Route)',
          actionLabel: 'Add New Damage Point',
          stats: [
            { label: 'Survey Route', value: 'KM 14.2' },
            { label: 'Logged Points', value: '18 Items' },
            { label: 'Sync Pending', value: '6 Items' },
          ],
          listItems: [
            { title: 'Severe Pothole (Grade 4)', subtitle: 'KM 14.220 • Outer Lane • Depth 8cm', status: 'Marked', tag: 'Pothole' },
            { title: 'Asphalt Alligator Cracking', subtitle: 'KM 14.850 • 12m Length', status: 'Marked', tag: 'Cracking' },
            { title: 'Guardrail Structural Damage', subtitle: 'KM 15.100 • Left Shoulder', status: 'Marked', tag: 'Safety' },
          ],
        },
      },
      {
        id: 'vis-form',
        title: 'Damage Inspection Entry',
        caption: 'Geo-tagged photographic evidence, dimension measurements, and severity rating',
        type: 'form',
        accentColor: '#E6A100',
        previewUiData: {
          headerTitle: 'Record Damage Inspection',
          subheading: 'Segment: Pantura Central Sector',
          badge: 'PHOTO VERIFIED',
          statusText: 'EXIF GPS Metadata embedded successfully',
          actionLabel: 'Save to Offline Database',
          stats: [
            { label: 'Severity', value: 'High' },
            { label: 'Photos', value: '3 Attached' },
            { label: 'Urgency', value: 'Level 1' },
          ],
          listItems: [
            { title: 'Damage Type Classification', subtitle: 'Transverse / Longitudinal Rutting', status: 'Verified', tag: 'Class B' },
            { title: 'Estimated Repair Volume', subtitle: 'Surface Area: 4.5m x 1.8m', status: 'Calculated', tag: 'Volume' },
            { title: 'Field Inspector Signature', subtitle: 'Inspector ID: PUPR-ENG-2022', status: 'Signed', tag: 'Audit' },
          ],
        },
      },
    ],
  },
  // Enterprise & GovTech Archived Projects
  {
    id: 'sirdk-ojk',
    title: 'SIRDK (Sistem Informasi Rapat Dewan Komisioner)',
    subtitle: 'Board of Commissioners Meeting & Executive Decision Briefing App',
    client: 'Otoritas Jasa Keuangan (OJK)',
    category: 'GovTech & Infrastructure',
    role: 'Android Developer',
    period: '2019 - 2021',
    isFeatured: false,
    platform: ['Android Native', 'Kotlin', 'Java'],
    summary: 'High-security mobile application engineered for the OJK Board of Commissioners to manage confidential meeting agendas, review executive financial regulatory dossiers, annotate confidential policies, and log voting outcomes.',
    architecturalHighlights: [
      'Enterprise-grade security with certificate pinning, root-jailbreak detection, and biometric locks',
      'Confidential document annotator with real-time watermark stamping to prevent data leakage',
      'Secure offline dossier synchronizer for executive offline travel briefings',
    ],
    challenges: [],
    metrics: [
      { label: 'Confidentiality', value: '100% Secure', detail: 'Zero regulatory leaks' },
      { label: 'Adoption', value: 'Executive Tier', detail: 'Used by OJK leadership' },
    ],
    techStack: {
      languages: ['Kotlin', 'Java'],
      frameworks: ['Android SDK'],
      stateManagement: ['MVVM / LiveData'],
      localDbAndStorage: ['Encrypted Room DB', 'SQLCipher'],
      architecturePatterns: ['Clean Architecture', 'MVP / MVVM'],
      integrations: ['Certificate Pinning', 'Biometric API', 'PDF Engine', 'RESTful API'],
    },
    screens: [],
  },
  {
    id: 'sippp-bph-migas',
    title: 'SIPPP (Sistem Pengawasan BBM)',
    subtitle: 'National Fuel Supply & Distribution Monitoring Platform',
    client: 'Badan Pengatur Hilir Minyak dan Gas Bumi (BPH MIGAS)',
    category: 'GovTech & Infrastructure',
    role: 'Android Developer',
    period: '2019 - 2021',
    isFeatured: false,
    platform: ['Android Native', 'Kotlin'],
    summary: 'National monitoring system for tracking fuel stock, quota allocations, supply logistics, and sales transactions across gas stations (SPBU) throughout the Indonesian archipelago.',
    architecturalHighlights: [
      'High-throughput data ingestion capturing daily fuel inventory records nationwide',
      'Automated quota anomaly detection flagging abnormal consumption spikes',
      'Real-time SPBU stock reporting pipeline with offline caching',
    ],
    challenges: [],
    metrics: [
      { label: 'Monitoring Scale', value: 'Nationwide', detail: 'SPBUs across Indonesia' },
      { label: 'Data Accuracy', value: '99.7%', detail: 'Inventory reconciliation' },
    ],
    techStack: {
      languages: ['Kotlin', 'Java'],
      frameworks: ['Android SDK'],
      stateManagement: ['MVVM', 'RxJava2'],
      localDbAndStorage: ['Room Database', 'Shared Preferences'],
      architecturePatterns: ['MVVM Architecture', 'Repository Pattern'],
      integrations: ['Retrofit2', 'OkHttp3', 'MPAndroidChart'],
    },
    screens: [],
  },
  {
    id: 'e-pegawai-kkp',
    title: 'Aplikasi E-Pegawai KKP',
    subtitle: 'Ministry Employee Management & Civil Service Attendance Portal',
    client: 'Kementerian Kelautan dan Perikanan (KKP)',
    category: 'GovTech & Infrastructure',
    role: 'Android Developer',
    period: '2020 - 2022',
    isFeatured: false,
    platform: ['Android Native', 'Kotlin'],
    summary: 'Comprehensive civil service mobile platform managing ministry personnel information, attendance verification across regional marine ports, career performance assessments, and official internal dispatches.',
    architecturalHighlights: [
      'Port location geofencing with offline biometric clock-in verification',
      'Modular personnel information management with encrypted staff profiles',
      'Official dispatch assignment workflow with digital signature verification',
    ],
    challenges: [],
    metrics: [
      { label: 'Civil Servants', value: '10K+ Staff', detail: 'Serving KKP ministry staff' },
      { label: 'Uptime', value: '99.9%', detail: 'Daily civil service operations' },
    ],
    techStack: {
      languages: ['Kotlin'],
      frameworks: ['Android SDK', 'Jetpack'],
      stateManagement: ['MVVM', 'LiveData'],
      localDbAndStorage: ['Room Database'],
      architecturePatterns: ['MVVM Architecture', 'Clean Architecture'],
      integrations: ['Geofencing API', 'Retrofit2', 'Firebase Messaging'],
    },
    screens: [],
  },
  {
    id: 'setneg-point',
    title: 'Setneg Point',
    subtitle: 'State Secretariat Employee Information & Administrative Workflow Portal',
    client: 'Kementerian Sekretariat Negara (Setneg)',
    category: 'GovTech & Infrastructure',
    role: 'Android Developer',
    period: '2021 - 2022',
    isFeatured: false,
    platform: ['Android Native', 'Java', 'Kotlin'],
    summary: 'Internal mobile application for the Ministry of State Secretariat managing state employee administrative data, executive agenda dispatches, performance appraisals, and official communications.',
    architecturalHighlights: [
      'High-security internal communication dispatches with encrypted local cache',
      'Multi-tier civil service performance appraisal workflows',
      'Integrated state event calendar and ministerial assignment tracker',
    ],
    challenges: [],
    metrics: [
      { label: 'Security Tier', value: 'High', detail: 'State administrative compliance' },
      { label: 'Workflow Speed', value: '4x Faster', detail: 'Paperless ministerial dispatches' },
    ],
    techStack: {
      languages: ['Java', 'Kotlin'],
      frameworks: ['Android SDK'],
      stateManagement: ['MVP / MVVM'],
      localDbAndStorage: ['SQLite', 'Encrypted Preferences'],
      architecturePatterns: ['MVP / MVVM Architecture'],
      integrations: ['Retrofit2', 'Glide', 'Firebase Push'],
    },
    screens: [],
  },
  {
    id: 'ojt-atr-bpn',
    title: 'On Job Training (OJT) ATR/BPN',
    subtitle: 'Land Registry Field Survey Training & Progress Tracking App',
    client: 'Kementerian Agraria dan Tata Ruang / Badan Pertanahan Nasional (ATR/BPN)',
    category: 'GovTech & Infrastructure',
    role: 'Android Developer',
    period: '2019 - 2020',
    isFeatured: false,
    platform: ['Android Native', 'Java'],
    summary: 'Field survey training management app for ATR/BPN cadets conducting land parcel measurements, irrigation area assessments, and field internship task submissions.',
    architecturalHighlights: [
      'Cadet field project submission portal with geo-tagged parcel photos',
      'Budget allocation tracking and supervisor assessment scoring',
      'Offline submission caching with automatic sync upon returning to camp',
    ],
    challenges: [],
    metrics: [
      { label: 'Cadets Trained', value: '1,000+', detail: 'Field surveyors nationwide' },
    ],
    techStack: {
      languages: ['Java'],
      frameworks: ['Android SDK'],
      stateManagement: ['MVP Pattern'],
      localDbAndStorage: ['SQLite Database'],
      architecturePatterns: ['MVP Pattern', 'Repository Pattern'],
      integrations: ['Google Maps API', 'Retrofit2'],
    },
    screens: [],
  },
];
